export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
export const SET_NICKNAME = 'SET_NICKNAME'
export const SET_ACCOUNT_ID = 'SET_ACCOUNT_ID'
export const SET_USERTOKEN = "SET_USERTOKEN"
export const SET_PROFILE_IMG = 'SET_PROFILE_IMG'
export const SET_FOLLOW_LIST = "SET_FOLLOW_LIST"