export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'
export const SET_CURRENT_AREA = 'SET_CURRENT_AREA'
export const SET_ZOOM_LEVEL = "SET_ZOOM_LEVEL"
export const ADD_MARKER = "ADD_MARKER"
export const DELETE_ALL_MARKERS = "DELETE_ALL_MARKERS"